sudo: required
dist: trusty
language: java
jdk:
  - openjdk11
addons:
  hostname: localhost
  install:
  - mkdir -p /tmp/uliul-dev
  - openssl aes-256-cbc -K $encrypted_123456_key -iv $encrypted_123456_iv -in /home/travis/build/uliul-dev/syslog4j-graylog2/.travic/sign.gpg.env -out /tmp/uliul-dev/private.key -d
  - gpg --import /tmp/uliul-dev/private.key
  - rm /tmp/uliul-dev/private.key
before_install:
  - sudo apt update
  - sudo apt install -y xmlstarlet gnupg
before_deploy:
  - echo "Deploying.."
  - git config --local user.name "Uliul"
  - git config --local user.email "uliul@gmail.com"
  - source VERSION
  - mvn package deploy -DperformRelease=true --settings settings.xml
deploy:
  - provider: releases
  - api_key: "$GH_TOKEN"
  - overwrite: true
  - file_glob: true
  - file:
    - "/home/travis/build/uliul-dev/syslog4j-graylog2/target/syslog4j-$version.jar"
    - "/home/travis/build/uliul-dev/syslog4j-graylog2/target/syslog4j-$version-javadoc.jar"
    - "/home/travis/build/uliul-dev/syslog4j-graylog2/target/syslog4j-$version-sources.jar"
    - "/home/travis/build/uliul-dev/syslog4j-graylog2/target/syslog4j-$version.jar.asc"
    - "/home/travis/build/uliul-dev/syslog4j-graylog2/target/syslog4j-$version-javadoc.jar.asc"
    - "/home/travis/build/uliul-dev/syslog4j-graylog2/target/syslog4j-$version-sources.jar.asc"
  skip_cleanup: true
  name: Syslog4j-$version
  on:
    tags: true
